macro(aoc_day day)
    set(DAY ${day})
    add_subdirectory(lib)
    if(BUILD_SOLUTIONS)
        add_subdirectory(src)
    endif()
    if(BUILD_TESTS AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/test)
        add_subdirectory(test)
    endif()
    if(BUILD_BENCHMARKS AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/benchmark)
        add_subdirectory(benchmark)
    endif()
endmacro(aoc_day )
