macro(aoc_add_library)
    file(GLOB_RECURSE SOURCES "*.cpp")
    add_library(${PROJECT_NAME}_day_${DAY}_lib STATIC ${SOURCES})
    target_link_libraries(${PROJECT_NAME}_day_${DAY}_lib PUBLIC ${PROJECT_NAME}_shared_lib)
    if(MSVC)
        target_compile_options(${PROJECT_NAME}_day_${DAY}_lib PRIVATE /std:c++latest)
    endif()
endmacro()
