macro(aoc_add_test)
    file(GLOB_RECURSE TEST_SOURCES *.cpp)    
    set(TESTS_EXE_NAME ${PROJECT_NAME}_day_${DAY}_tests)
    add_executable(${TESTS_EXE_NAME} ${TEST_SOURCES})
    include(AddDependency)
    add_github_dependency_by_tag(googletest google/googletest v1.15.2)
    set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    target_link_libraries(${TESTS_EXE_NAME} GTest::gtest_main GTest::gmock_main ${PROJECT_NAME}_day_${DAY}_lib)
    include(GoogleTest)
    gtest_discover_tests(${TESTS_EXE_NAME})
endmacro()