name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}
    strategy:
      matrix:
        operatingsystems: [windows-latest, ubuntu-latest, macos-latest]
        buildtypes: [Release]
    steps:
    - uses: actions/checkout@v4

    # Windoof setup
    - name: Cache Chocolatey packages
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-choco-${{ hashFiles('**/Build.yaml') }}

    - name: Cache MSVC
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: C:\Program Files (x86)\Microsoft Visual Studio
        key: ${{ runner.os }}-msvc-${{ hashFiles('**/Build.yaml') }}

    - name: Setup Ninja under Windows
      if: runner.os == 'Windows'
      run: choco install ninja -y

    - name: Setup MSVC under Windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # Schlinux setup
    - name: Cache apt packages
      if: runner.os == 'Linux'
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/apt
          ~/.local/share/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Build.yaml') }}
    
    - name: Setup Dependencies under Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get -y install \
          cmake \
          ninja-build \
          gcc-13 \
          g++-13 \
          ${NULL+}
      env:
        DEBIAN_FRONTEND: noninteractive

    # SchmockOS setup
    - name: Setup Dependencies under MacOS
      if: runner.os == 'macOS'
      run: |
        brew install \
          ninja \
          ${NULL+}
          
    - name: Configure CMake under Windows
      if: runner.os == 'Windows'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Configure Cmake under Linux or MacOS
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: cmake -D CMAKE_C_COMPILER=gcc-13 -D CMAKE_CXX_COMPILER=g++-13 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    
    - name: Building Project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      