name: Tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}
    strategy:  
      matrix:
        buildtypes: [Release]
    steps:
    - uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja -y

    - name: Setup MSVC under Windows
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake        
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DBUILD_TESTS=ON

    - name: Build tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
